// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_assignments_new from "./routes/admin/assignments/new.tsx";
import * as $admin_dashboard from "./routes/admin/dashboard.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_questions_id_ from "./routes/admin/questions/[id].tsx";
import * as $admin_questions_index from "./routes/admin/questions/index.tsx";
import * as $admin_questions_new from "./routes/admin/questions/new.tsx";
import * as $admin_students_id_ from "./routes/admin/students/[id].tsx";
import * as $admin_students_id_history from "./routes/admin/students/[id]/history.tsx";
import * as $admin_students_index from "./routes/admin/students/index.tsx";
import * as $admin_students_new from "./routes/admin/students/new.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $student_assignment_id_ from "./routes/student/assignment/[id].tsx";
import * as $student_assignment_id_results from "./routes/student/assignment/[id]/results.tsx";
import * as $student_assignments_index from "./routes/student/assignments/index.tsx";
import * as $student_dashboard from "./routes/student/dashboard.tsx";
import * as $student_index from "./routes/student/index.tsx";
import * as $student_practice_index from "./routes/student/practice/index.tsx";
import * as $student_progress_index from "./routes/student/progress/index.tsx";
import * as $student_select_avatar from "./routes/student/select-avatar.tsx";
import * as $AvatarImage from "./islands/AvatarImage.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $PracticeButtons from "./islands/PracticeButtons.tsx";
import * as $QuestionCreationForm from "./islands/QuestionCreationForm.tsx";
import * as $QuestionList from "./islands/QuestionList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/assignments/new.tsx": $admin_assignments_new,
    "./routes/admin/dashboard.tsx": $admin_dashboard,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/questions/[id].tsx": $admin_questions_id_,
    "./routes/admin/questions/index.tsx": $admin_questions_index,
    "./routes/admin/questions/new.tsx": $admin_questions_new,
    "./routes/admin/students/[id].tsx": $admin_students_id_,
    "./routes/admin/students/[id]/history.tsx": $admin_students_id_history,
    "./routes/admin/students/index.tsx": $admin_students_index,
    "./routes/admin/students/new.tsx": $admin_students_new,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/student/assignment/[id].tsx": $student_assignment_id_,
    "./routes/student/assignment/[id]/results.tsx":
      $student_assignment_id_results,
    "./routes/student/assignments/index.tsx": $student_assignments_index,
    "./routes/student/dashboard.tsx": $student_dashboard,
    "./routes/student/index.tsx": $student_index,
    "./routes/student/practice/index.tsx": $student_practice_index,
    "./routes/student/progress/index.tsx": $student_progress_index,
    "./routes/student/select-avatar.tsx": $student_select_avatar,
  },
  islands: {
    "./islands/AvatarImage.tsx": $AvatarImage,
    "./islands/Counter.tsx": $Counter,
    "./islands/PracticeButtons.tsx": $PracticeButtons,
    "./islands/QuestionCreationForm.tsx": $QuestionCreationForm,
    "./islands/QuestionList.tsx": $QuestionList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
